ThueTro/Models/NhaTro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ThueTro.Models
{
    public class NhaTro
    {
        [Key]
        public int IDNha { get; set; }
        [StringLength(500)]
        
        public string Tenduong { get; set; }
        public string DienTich { get; set; }
        [StringLength(50)]
        public string TenChuNha { get; set; }
        public string SDT { get; set; }
        [StringLength(500)]
        public string CTNha { get; set; }
        [StringLength(500)]
        public string GioiThieu { get; set; }
        [StringLength(50)]
        public string Gia { get; set; }
        public string image { get; set; }
        public string image2 { get; set; }
        public string image3 { get; set; }
        public int ratting { get; set; }
        public DiaDiem diaDiem { get; set; }
        public string IDQuann { get; set; }
        public DateTime DateTime { get; set; }

    }
}

ThueTro/Controllers/NhaTroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThueTro.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;
using System.Data;
using System.Data.Entity;
using System.Net;

namespace ThueTro.Controllers
{
    public class NhaTroController : Controller
    {
        public readonly ApplicationDbContext db = new ApplicationDbContext();

        //IList<NhaTro> n = new List<NhaTro>() 
        //{
        //    var nhanvien = (from s in _db.NHANVIENs select s).ToList();
        //};                
        [HttpGet]
        [Authorize(Roles ="Admin")]
        // GET: NhaTro

        public ActionResult Index(int ?page)
        {
            var total = db.NhaTros
                .Select(a => a.IDNha)
                .ToList().Count;
            ViewBag.total = total;
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            return View(db.NhaTros.ToList().OrderBy(n => n.IDNha).ToPagedList(pageNumber, pageSize));
        }
        
        [HttpGet]
        // GET: NhaTro/Details/5
        public ActionResult Details(int id)
        {
            NhaTro nt = db.NhaTros.SingleOrDefault(n => n.IDNha == id);
            ViewBag.IDNha = nt.IDNha;
            if(nt == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(nt);
        }
        [HttpGet]
        // GET: NhaTro/Create
        public ActionResult Create()
        {
            //ViewBag.IDQuan = new SelectList(db.DiaDiems.ToList().OrderBy(n => n.TenQuan), "IDQuan", "TenQuan");
            //var nt = new NhaTro
            //{
            //    DiaDiems = db.DiaDiems.ToList()
            //};
            ViewBag.DiaDiemIdQuan = new SelectList(db.DiaDiems, "IDQuan", "TenQuan");
            return View();
        }

        // POST: NhaTro/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [Authorize]
        public ActionResult Create(NhaTro nhatro, HttpPostedFileBase anh)
        {
            ViewBag.DiaDiemIdQuan = new SelectList(db.DiaDiems, "IDQuan", "TenQuan");
            if (anh == null)
            {
                ViewBag.Thongbao = "Bạn chưa chọn ảnh";
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var fileName = Path.GetFileName(anh.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/HinhAnh/"), fileName);
                    if (System.IO.File.Exists(path))
                    {
                        ViewBag.Thongbao = "Hình ảnh đã tồn tại";
                    }
                    else
                    {
                        anh.SaveAs(path);
                    }
                    nhatro.image = fileName;
                    db.NhaTros.Add(nhatro);
                    db.SaveChanges();                    
                }               
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        // GET: NhaTro/Edit/5
        public ActionResult Edit(int? id, bool? saveChangesError = false)
        {
            NhaTro nt = db.NhaTros.Find(id);            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }                        
            if (nt == null)
            {
                return HttpNotFound();
            }
            ViewBag.DiaDiemIdQuan = new SelectList(db.DiaDiems, "IDQuan", "TenQuan", nt.DiaDiemIdQuan);
            return View(nt);     
        }

        // POST: NhaTro/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]       
        public ActionResult Edit(NhaTro nhatro, HttpPostedFileBase fileUpload)
        {
            ViewBag.DiaDiemIdQuan = new SelectList(db.DiaDiems, "IDQuan", "TenQuan");
            //if(fileUpload != null)
            //{
            //    if (ModelState.IsValid)
            //    {
            //        var fileName = Path.GetFileName(fileUpload.FileName);
            //        var path = Path.Combine(Server.MapPath("~/Content/HinhAnh/"), fileName);
            //        if (System.IO.File.Exists(path))
            //        {
            //            ViewBag.Thongbao = "Hình ảnh đã tồn tại";
            //        }
            //        else
            //        {
            //            fileUpload.SaveAs(path);
            //        }
            //        nhatro.image = fileName;
                    db.Entry(nhatro).State = EntityState.Modified;
                    db.SaveChanges();
                //}
                return RedirectToAction("Index");
            //}
            //else
            //{
            //    ViewBag.Thongbao = "Bạn chưa chọn ảnh";
            //    return View();
            //}
        }
        [HttpGet]
        // GET: NhaTro/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhaTro nt = db.NhaTros.Find(id);
            if (nt == null)
            {
                return HttpNotFound();
            }
            return View(nt);
        }

        // POST: NhaTro/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
                NhaTro nt = db.NhaTros.SingleOrDefault(n => n.IDNha == id);
                ViewBag.IDNha = nt.IDNha;
                if (nt == null)
                {
                    return HttpNotFound();
                }
                db.NhaTros.Remove(nt);
                db.SaveChanges();
                return RedirectToAction("Index");
        }
    }
}

ThueTro/Views/NhaTro/Create.cshtml
@*@model ThueTro.Models.NhaTro*@
@model ThueTro.Models.NhaTro

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Đăng nhà trọ mới</h2>

@using (Html.BeginForm("Create","NhaTro", FormMethod.Post, new {@enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()   
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Tenduong, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tenduong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tenduong, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DienTich, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DienTich, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DienTich, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenChuNha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenChuNha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenChuNha, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.CTNha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.CTNha, htmlAttributes: new { style = "width: 1080px; height: 200px; " })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GioiThieu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.GioiThieu, htmlAttributes: new { style = "width: 1080px; height: 200px; " })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="anh" />
            @ViewBag.Thongbao
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DiaDiemIdQuan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DiaDiemIdQuan", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DiaDiemIdQuan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button style="width: 105px" type="submit" class="btn btn-success" ;return false;><span style="margin-right: 5px" class="glyphicon glyphicon-save"></span>Xác nhận</button>
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Về trang quản lý", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ThueTro/Views/NhaTro/Delete.cshtml
@model ThueTro.Models.NhaTro

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Xóa thông tin nhà trọ</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tenduong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tenduong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienTich)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienTich)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenChuNha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenChuNha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CTNha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CTNha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiThieu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiThieu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img src="@Url.Content("~/Content/HinhAnh/" + Model.image)" style="height:150px; width:150px; margin:10px;"/>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DiaDiemIdQuan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaDiemIdQuan)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <h4>Bạn thực sự muốn xóa?</h4>
    <button style="width: 105px" type="submit" class="btn btn-danger" ;return false;><span style="margin-right: 5px" class="glyphicon glyphicon-trash"></span>Xóa</button> |
    @Html.ActionLink("Về trang quản lý", "Index")
</div>
    }
</div>

ThueTro/Views/NhaTro/Details.cshtml
@model ThueTro.Models.NhaTro

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin chi tiết nhà trọ</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tenduong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tenduong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienTich)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienTich)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenChuNha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenChuNha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CTNha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CTNha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiThieu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiThieu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img src="@Url.Content("~/Content/HinhAnh/" + Model.image)" style="height:150px; width:150px; margin:10px;"/>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DiaDiemIdQuan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaDiemIdQuan)
        </dd>

    </dl>
</div>
<p>
    <button style="width: 130px" type="button" class="btn btn-warning" onclick="location.href = '@Url.Action("Edit", "NhaTro", new { id = Model.IDNha })';return false;"><span style="margin-right: 5px" class="glyphicon glyphicon-pencil"></span>Sửa thông tin</button> |
    @Html.ActionLink("Về trang quản lý", "Index")
</p>

ThueTro/Views/NhaTro/Edit.cshtml
@model ThueTro.Models.NhaTro

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sửa thông tin nhà trọ</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IDNha)

    <div class="form-group">
        @Html.LabelFor(model => model.Tenduong, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tenduong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tenduong, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DienTich, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DienTich, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DienTich, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenChuNha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenChuNha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenChuNha, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.CTNha, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.CTNha, htmlAttributes: new { style = "width: 1080px; height: 200px; " })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GioiThieu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.GioiThieu, htmlAttributes: new { style = "width: 1080px; height: 200px; " })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            Chọn ảnh mới
            @*<input type="file" name="fileUpload" />*@
            @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
            @ViewBag.Thongbao
        </div>
    </div>

    @*<input type="file" name="anh" />*@
    @*<img src="@Url.Content("~/Content/HinhAnh/" + Model.image)" style="height:150px; width:150px;" />*@

    <div class="form-group">
        @Html.LabelFor(model => model.DiaDiemIdQuan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DiaDiemIdQuan", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DiaDiemIdQuan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button style="width: 105px" type="submit" class="btn btn-warning" ;return false;><span style="margin-right: 5px" class="glyphicon glyphicon-check"></span>Lưu</button>
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Về trang quản lý", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ThueTro/Views/NhaTro/Index.cshtml
@*@using ThueTro.Models;*@
@using PagedList.Mvc;
@model PagedList.PagedList<ThueTro.Models.NhaTro>

@helper Truncate(string input, int length)
{
    if (input.Length < length)
    {
        @input
    }
    else
    {
        @input.Substring(0, length)<text>...</text>
    }
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-primary" style="width:100%">
    <div class="panel-heading">
        <span style="font-size: 30px; font-style:oblique"><span style="font-size:larger;"><span style="margin-right: 5px" class="glyphicon glyphicon-star"></span>Quản lý nhà trọ</span></span>
    </div>
</div>
<p>
    @*@Html.ActionLink("Đăng tin", "Create")*@
    <button type="button" style="margin:3px; width:32.8%" class="btn btn-success col-lg-3 col-xs-3" onclick="location.href='@Url.Action("Create", "NhaTro")';return false;"><span style="font-size:larger;"><span style="margin-right: 5px" class="glyphicon glyphicon-plus"></span>Đăng tin</span></button>
</p>
<br />
<br />
<br />
<h4>Tổng số nhà trọ hiện có: @ViewBag.total</h4>
<table class="table" border="1">
    <tr>
        <th style="width:5%; max-width: 100%; font-weight:bolder; text-align: center; vertical-align: middle">STT</th>
        <th style="width:11%; max-width: 100%; font-weight:bolder; text-align: center; vertical-align: middle">Tên đường</th>
        <th style="width:5%; max-width: 100%; font-weight:bolder; text-align: center; vertical-align: middle">Diện tích</th>
        <th style="width:5%; max-width: 100%; font-weight:bolder; text-align: center; vertical-align: middle">Tên chủ nhà</th>
        <th style="width:8%; max-width: 100%; font-weight:bolder; text-align: center; vertical-align: middle">SDT liên hệ</th>
        <th style="width:16%; max-width: 100%; font-weight:bolder; text-align: center; vertical-align: middle">Chi tiết nhà</th>
        <th style="width:16%; max-width: 100%; font-weight:bolder; text-align: center; vertical-align: middle">Giới thiệu</th>
        <th style="width:5%; max-width: 100%; font-weight:bolder; text-align: center; vertical-align: middle">Giá</th>
        <th style="width:14%; max-width: 100%; font-weight:bolder; text-align: center; vertical-align: middle">Ảnh</th>
        <th style="width:5%; max-width: 100%; font-weight:bolder; text-align: center; vertical-align: middle">Quận</th>
        <th style="width:10%; max-width: 100%; font-weight:bolder; text-align: center; vertical-align: middle">Chức năng</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align: center; vertical-align: middle">
                @Html.DisplayFor(modelItem => item.IDNha)
            </td>
            <td style="text-align: center; vertical-align: middle">
                @Html.DisplayFor(modelItem => item.Tenduong)
            </td>
            <td style="text-align: center; vertical-align: middle">
                @Html.DisplayFor(modelItem => item.DienTich)
            </td>
            <td style="text-align: center; vertical-align: middle">
                @Html.DisplayFor(modelItem => item.TenChuNha)
            </td>
            <td style="text-align: center; vertical-align: middle">
                @Html.DisplayFor(modelItem => item.SDT)
            </td>
            <td style="text-align: center; vertical-align: middle">
                @Truncate(item.CTNha, 70)
            </td>
            <td style="text-align: center; vertical-align: middle">
                @Truncate(item.GioiThieu, 70)
            </td>
            <td style="text-align: center; vertical-align: middle">
                @Html.DisplayFor(modelItem => item.Gia)
            </td>
            <td>
                <img src="@Url.Content("~/Content/HinhAnh/" + item.image)" style="height:150px; width:150px;" />
                @*<img src="@Url.Content(Model.image)" style="height:150px; width:150px; margin:10px;"/>*@
            </td>
            <td style="text-align: center; vertical-align: middle">
                @Html.DisplayFor(modelItem => item.DiaDiemIdQuan)
            </td>
            <td>
                <button style="width: 95px" type="button" class="btn btn-warning" onclick="location.href = '@Url.Action("Edit", "NhaTro", new { id = item.IDNha })';return false;"><span style="margin-right: 5px" class="glyphicon glyphicon-pencil"></span>Sửa</button>
                <br />
                --------------------                
                <button style="width: 95px" type="button" class="btn btn-info" onclick="location.href = '@Url.Action("Details", "NhaTro", new { id = item.IDNha })';return false;"><span style="margin-right: 5px" class="glyphicon glyphicon-align-justify"></span>Chi tiết</button>
                <br />
                --------------------               
                <button style="width: 95px" type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("Delete", "NhaTro", new { id = item.IDNha })' ;return false;"><span style="margin-right: 5px" class="glyphicon glyphicon-trash"></span>Xóa</button>
            </td>
        </tr>
    }
</table>
@*Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount*@
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>   